In [2]:
import pandas as pd
from pathlib import Path

chemin_csv = Path("data/titanic_propre.csv")

if not chemin_csv.exists():
    chemin_csv = Path("/Users/ytmaiga/heticdev/exercice_python/exercice-08/data/titanic_propre.csv")

titanic_propre = pd.read_csv(chemin_csv)

print("Nombre de passagers :", len(titanic_propre))

Nombre de passagers : 891

In [3]:
ports = pd.DataFrame({
    "embark_town": ["Cherbourg", "Queenstown", "Southampton"],
    "pays": ["France", "Irlande", "Angleterre"]
})

display(ports)

   embark_town        pays
0    Cherbourg      France
1   Queenstown     Irlande
2  Southampton  Angleterre

In [4]:
titanic_avec_ports = titanic_propre.merge(
    ports,
    on="embark_town",
    how="left"
)

print("Lignes avant la jointure :", len(titanic_propre))
print("Lignes après la jointure :", len(titanic_avec_ports))

Lignes avant la jointure : 891
Lignes après la jointure : 891

La jointure left conserve tous les passagers du Titanic. Comme chaque port apparaît une seule fois dans la table ports, le nombre de lignes reste inchangé.

In [5]:
statistiques_par_pays = (
    titanic_avec_ports.groupby("pays")
    .agg(
        nombre_passagers=("survived", "count"),
        taux_survie=("survived", "mean")
    )
)

statistiques_par_pays["taux_survie"] *= 100

display(statistiques_par_pays.round(2))

            nombre_passagers  taux_survie
pays
Angleterre               646        33.90
France                   168        55.36
Irlande                   77        38.96

Le tableau présente le nombre de passagers et leur taux de survie par pays d'embarquement. Il permet de comparer les résultats entre la France, l'Irlande et l'Angleterre.

In [6]:
ports_sans_queenstown = ports[
    ports["embark_town"] != "Queenstown"
]

display(ports_sans_queenstown)

   embark_town        pays
0    Cherbourg      France
2  Southampton  Angleterre

In [7]:
titanic_inner = titanic_propre.merge(
    ports_sans_queenstown,
    on="embark_town",
    how="inner"
)

print("Nombre de lignes avec inner :", len(titanic_inner))

Nombre de lignes avec inner : 814

In [8]:
titanic_left = titanic_propre.merge(
    ports_sans_queenstown,
    on="embark_town",
    how="left"
)

print("Nombre de lignes avec left :", len(titanic_left))
print("Pays manquants après la jointure :",
      titanic_left["pays"].isna().sum())

Nombre de lignes avec left : 891
Pays manquants après la jointure : 77

Après avoir retiré Queenstown de la table ports, la jointure inner exclut les passagers ayant embarqué à Queenstown, car aucune correspondance n'existe. La jointure left conserve tous les passagers, mais leur pays devient manquant. Cela montre que le type de jointure détermine quelles lignes sont conservées.